---
- hosts: all
  #become: yes
  gather_facts: yes
  #pre_tasks:
  #  - name: "Install devops dependencies"
  #    become: yes
  #    apt:
  #      name: "{{ item }}"
  #      state: present
  #      update_cache: yes
  #      cache_valid_time: 3600
  #    with_items:
  #      # For capybara and poltergeist
  #      - zlib1g-dev
  roles:
    - role: andrewrothstein.vagrant
      become: yes
      tags:
        - vagrant
    - role: andrewrothstein.packer
      become: yes
      tags:
        - vagrant

  tasks:
    - block:
      - name: Add ansible ppa
        become: yes
        apt_repository:
          repo: 'ppa:ansible/ansible'
          update_cache: yes
      - name: "Install devops needed packages"
        become: yes
        apt:
          name: "{{ item }}"
          state: present
          update_cache: yes
          cache_valid_time: 3600
        with_items:
          - ansible
          - ruby
          - ruby-dev
          - gem
          - ruby-serverspec
          - ruby-capybara
          - cucumber
      - name: "Install vagrant-plugins"
        command: "vagrant plugin install {{item}}"
        with_items:
          - vagrant-lxc
      - name: "Install ruby gems"
        become: yes
        gem:
          name: "{{item}}"
          user_install: no
        with_items:
          - inspec
          #- serverspec
          #- capybara
          #- selenium-webdriver
          #- cucumber
          #- rspec
          #- sinatra
          #- poltergeist
          #- rspec-expectations
          #- launchy
          #- rest-client
          #- test-kitchen
          #- kitchen-ansible
          #- kitchen-salt
          #- kitchen-vagrant
          #- kitchen-docker
          #- kitchen-sync
          #- kitchen-verifier-serverspec
          #- kitchen-lxc
          #- kitchen-inspec
          #- fog
          #- foodcritic
          #- thor-foodcritic
        tags:
          - ruby
      - name: "Install testinfra virtualenv"
        pip:
          name: "{{item}}"
          virtualenv: "{{ansible_user_dir}}/.testinfra_venv"
          virtualenv_python: python3
        with_items:
          - testinfra
          - paramiko
          - pytest-xdist
        tags:
          - python
      - name: "Install molecule virtualenv"
        pip:
          name: "{{item}}"
          virtualenv: "{{ansible_user_dir}}/.molecule_venv"
          virtualenv_python: python3
        with_items:
          - molecule
        tags:
          - python
